Manifestv2

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -7,225 +7,103 @@
 source _common.sh
 source /usr/share/yunohost/helpers
 
-#=================================================
-# MANAGE SCRIPT FAILURE
-#=================================================
-
-# Exit if an error occurs during the execution of the script
-ynh_abort_if_errors
-
-#=================================================
-# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
-#=================================================
-ynh_script_progression --message="Validating installation parameters..."
-
-# Path for e.g. "static" files, served by nginx:
-test ! -e "$public_path" || ynh_die --message="This path already contains a folder"
-
-# Path for own config files, e.g.: Django's settings.py:
-test ! -e "$final_path" || ynh_die --message="This path already contains a folder"
-
-# Register (book) web path
-ynh_webpath_register --app="$app" --domain="$domain" --path_url="$path_url"
 
 mkdir -p "$public_path/media" "$public_path/static"
-mkdir -p "$final_path"
+mkdir -p "$install_dir"
 
 mkdir -p "$log_path"
-touch "${log_file}"
-
-#=================================================
-# STORE SETTINGS FROM MANIFEST
-#=================================================
-ynh_script_progression --message="Storing installation settings..."
-
-ynh_app_setting_set --app="$app" --key=admin --value="$admin"
-ynh_app_setting_set --app="$app" --key=public_path --value="$public_path"
-ynh_app_setting_set --app="$app" --key=final_path --value="$final_path"
-ynh_app_setting_set --app="$app" --key=log_path --value="$log_file"
-
-ynh_app_setting_set --app="$app" --key=domain --value="$domain"
-ynh_app_setting_set --app="$app" --key=path --value="$path_url"
-
-# Find a free port
-port=$(ynh_find_port --port=8000)
-# Set port as application setting
-# https://yunohost.org/en/contribute/packaging_apps/helpers
-# https://github.com/YunoHost/yunohost/blob/dev/helpers/setting
-ynh_app_setting_set --app="$app" --key=port --value="$port"
-
-db_pwd=$(ynh_app_setting_get --app="$app" --key=psqlpwd)
+touch "${/var/log/$app/$app.log}"
 
 redis_db=$(ynh_redis_get_free_db)
 ynh_app_setting_set --app="$app" --key=redis_db --value="$redis_db"
 
-#-------------------------------------------------
-# config_panel.toml settings:
+# 'debug_enabled' -> '__DEBUG_ENABLED__' -> settings.DEBUG
+debug_enabled="0"
+
+# 'log_level' -> '__LOG_LEVEL__' -> settings.LOG_LEVEL
+log_level="WARNING"
+
+# 'admin_email' -> '__ADMIN_EMAIL__' add in settings.ADMINS
+admin_email="${admin}@${domain}"
+
+# 'default_from_email' -> '__DEFAULT_FROM_EMAIL__' -> settings.DEFAULT_FROM_EMAIL
+default_from_email="${app}@${domain}"
+
 
 ynh_app_setting_set --app="$app" --key=debug_enabled --value="$debug_enabled"
 ynh_app_setting_set --app="$app" --key=log_level --value="$log_level"
-ynh_app_setting_set --app="$app" --key=admin_email --value="$admin_email"
+#REMOVEME? ynh_app_setting_set --app="$app" --key=admin_email --value="$admin_email"
 ynh_app_setting_set --app="$app" --key=default_from_email --value="$default_from_email"
 
 #=================================================
-# STANDARD MODIFICATIONS
+# INSTALLATION
 #=================================================
-# INSTALL DEPENDENCIES
-#=================================================
-ynh_script_progression --message="Installing $app dependencies..." --weight=20
+ynh_script_progression --message="Installing project via pip..." --weight=45
 
-ynh_exec_warn_less ynh_install_app_dependencies "$pkg_dependencies"
+_install_fmd_venv
 
-#=================================================
-# CREATE A PostgreSQL DATABASE
-#=================================================
-ynh_script_progression --message="Creating a PostgreSQL database..."
+mkdir -p "$install_dir/public/media" "$install_dir/public/static"
 
-db_name=$(ynh_sanitize_dbid --db_name="$app")
-db_user=$db_name
-ynh_app_setting_set --app="$app" --key=db_name --value="$db_name"
+chmod o-rwx "$install_dir"
+chown -R "$app:www-data" "$install_dir"
 
-ynh_psql_test_if_first_run
+mkdir -p "$log_path"
+touch "$log_file"
 
-# Initialize database and store postgres password for upgrade
-ynh_psql_setup_db --db_user="$db_user" --db_name="$db_name"
-
-#=================================================
-# NGINX CONFIGURATION
-#=================================================
-ynh_script_progression --message="Configuring nginx web server..."
-
-# Create a dedicated nginx config
-# https://yunohost.org/en/contribute/packaging_apps/helpers
-# https://github.com/YunoHost/yunohost/blob/dev/helpers/nginx
-ynh_add_nginx_config "public_path" "port"
-
-#=================================================
-# CREATE DEDICATED USER
-#=================================================
-ynh_script_progression --message="Configuring system user '$app'..."
-
-# A home directory for venv and settings etc.
-ynh_system_user_create --username="$app" --home_dir="$final_path" --use_shell
-
-#=================================================
-# PYTHON VIRTUALENV
-#=================================================
-ynh_script_progression --message="Create Python virtualenv..." --weight=5
-
-# Always recreate everything fresh with current python version
-ynh_secure_remove "${final_path}/venv"
-
-# Skip pip because of: https://github.com/YunoHost/issues/issues/1960
-python3 -m venv --without-pip "${final_path}/venv"
-
-cp ../conf/requirements.txt "$final_path/requirements.txt"
-chown -R "$app:" "$final_path"
-
-#=================================================
-# PIP INSTALLATION
-#=================================================
-ynh_script_progression --message="Install project via pip..." --weight=45
-
-#run source in a 'sub shell'
-(
-	set +o nounset
-	source "${final_path}/venv/bin/activate"
-	set -o nounset
-	ynh_exec_as $app $final_path/venv/bin/python3 -m ensurepip
-	ynh_exec_as $app $final_path/venv/bin/pip3 install --upgrade wheel pip setuptools
-	ynh_exec_as $app $final_path/venv/bin/pip3 install --no-deps -r "$final_path/requirements.txt"
-)
+chmod o-rwx "$log_path"
+chown -R "$app:$app" "$log_path"
 
 #=================================================
 # copy config files
 # ================================================
 ynh_script_progression --message="Create $app configuration files..."
 
-ynh_add_config --template="gunicorn.conf.py" --destination="$final_path/gunicorn.conf.py"
+ynh_add_config --template="gunicorn.conf.py" --destination="$install_dir/gunicorn.conf.py"
 
-ynh_add_config --template="manage.py" --destination="$final_path/manage.py"
-chmod +x "$final_path/manage.py"
+ynh_add_config --template="manage.py" --destination="$install_dir/manage.py"
+chmod +x "$install_dir/manage.py"
 
-ynh_add_config --template="settings.py" --destination="$final_path/settings.py"
-ynh_add_config --template="setup_user.py" --destination="$final_path/setup_user.py"
-ynh_add_config --template="urls.py" --destination="$final_path/urls.py"
-ynh_add_config --template="wsgi.py" --destination="$final_path/wsgi.py"
+ynh_add_config --template="settings.py" --destination="$install_dir/settings.py"
+ynh_add_config --template="setup_user.py" --destination="$install_dir/setup_user.py"
+ynh_add_config --template="urls.py" --destination="$install_dir/urls.py"
+ynh_add_config --template="wsgi.py" --destination="$install_dir/wsgi.py"
 
-touch "$final_path/local_settings.py"
+touch "$install_dir/local_settings.py"
 
 #=================================================
 # MIGRATE / COLLECTSTATIC / CREATEADMIN
 #=================================================
 ynh_script_progression --message="migrate/collectstatic/createadmin..." --weight=10
 
-cd "$final_path" || exit
+pushd "$install_dir"
+    # Just for debugging:
+    ynh_exec_as "$app" "$venvpython" ./manage.py diffsettings
 
-# Just for debugging:
-./manage.py diffsettings
+    ynh_exec_as "$app" "$venvpython" ./manage.py migrate --no-input
+    ynh_exec_as "$app" "$venvpython" ./manage.py collectstatic --no-input
 
-./manage.py migrate --no-input
-./manage.py collectstatic --no-input
+    # Create/update Django superuser (set unusable password, because auth done via SSOwat):
+    ynh_exec_as "$app" "$venvpython" ./manage.py create_superuser --username="$admin" --email="$(ynh_user_get_info "$admin" mail)"
 
-# Create/update Django superuser (set unusable password, because auth done via SSOwat):
-./manage.py create_superuser --username="$admin" --email="$(ynh_user_get_info "$admin" mail)"
-
-# Check the configuration
-# This may fail in some cases with errors, etc., but the app works and the user can fix issues later.
-./manage.py check --deploy || true
-
+    # Check the configuration
+    # This may fail in some cases with errors, etc., but the app works and the user can fix issues later.
+    ynh_exec_as "$app" "$venvpython" ./manage.py check --deploy || true
+popd
 
 #=================================================
-# SETUP LOGROTATE
+# SYSTEM CONFIGURATION
 #=================================================
-ynh_script_progression --message="Configuring log rotation..."
+ynh_script_progression --message="Adding system configurations related to $app..." --weight=1
+
+# Create a dedicated nginx config
+ynh_add_nginx_config
+
+# Create a dedicated systemd config
+ynh_add_systemd_config --service="$app" --template="systemd.service"
+yunohost service add "$app" --log="/var/log/$app/$app.log"
 
 # Use logrotate to manage app-specific logfile(s)
-ynh_use_logrotate "$log_file"
-
-#=================================================
-# INTEGRATE SERVICE IN YUNOHOST
-#=================================================
-ynh_script_progression --message="Integrating service in YunoHost..."
-
-yunohost service add $app --log="${log_file}"
-
-#=================================================
-# GENERIC FINALIZATION
-#=================================================
-# SECURE FILES AND DIRECTORIES
-#=================================================
-
-# Set permissions to app files
-chown -R "$app:" "$log_path"
-chown -R "$app:www-data" "$public_path"
-chown -R "$app:" "$final_path"
-
-chmod o-rwx "$log_path"
-chmod o-rwx "$public_path"
-chmod o-rwx "$final_path"
-
-#=================================================
-# SETUP SYSTEMD
-#=================================================
-ynh_script_progression --message="Configuring systemd service '$app'..." --weight=5
-
-# https://yunohost.org/en/contribute/packaging_apps/helpers
-# https://github.com/YunoHost/yunohost/blob/dev/helpers/systemd
-ynh_add_systemd_config --service="$app" --template="systemd.service"
-
-#=================================================
-# SETUP SSOWAT
-#=================================================
-ynh_script_progression --message="Configuring SSOwat..."
-
-# Make app public if necessary or protect it
-if [ $is_public -eq 1 ]
-then
-	# Everyone can access the app.
-	# The "main" permission is automatically created before the install script.
-	ynh_permission_update --permission "main" --add "visitors"
-fi
+ynh_use_logrotate
 
 #=================================================
 # Start the app server via systemd
@@ -233,13 +111,6 @@ fi
 ynh_script_progression --message="Starting systemd service '$app'..." --weight=5
 
 ynh_systemd_action --service_name="$app" --action="start"
-
-#=================================================
-# RELOAD NGINX
-#=================================================
-ynh_script_progression --message="Reloading nginx web server..."
-
-ynh_systemd_action --service_name="nginx" --action="reload"
 
 #=================================================
 # END OF SCRIPT
