Update project setup via manageprojects

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -7,31 +7,27 @@
 source _common.sh
 source /usr/share/yunohost/helpers
 
-#=================================================
-# STANDARD UPGRADE STEPS
-#=================================================
-# ENSURE DOWNWARD COMPATIBILITY
-#=================================================
-ynh_script_progression --message="Ensuring downward compatibility..." --weight=1
+#-------------------------------------------------
+# config_panel.toml settings:
 
-if [ -z "${debug_enabled:-}" ]; then
-    debug_enabled="0"
-    ynh_app_setting_set --app="$app" --key=debug_enabled --value="$debug_enabled"
+if [ -z "$debug_enabled" ]; then
+	debug_enabled="0"
+	ynh_app_setting_set --app=$app --key=debug_enabled --value="$debug_enabled"
 fi
 
-if [ -z "${log_level:-}" ]; then
-    log_level="WARNING"
-    ynh_app_setting_set --app="$app" --key=log_level --value="$log_level"
+if [ -z "$log_level" ]; then
+	log_level="WARNING"
+	ynh_app_setting_set --app=$app --key=log_level --value="$log_level"
 fi
 
-if [ -z "${admin_email:-}" ]; then
-    admin_email="${admin}@${domain}"
-    ynh_app_setting_set --app="$app" --key=admin_email --value="$admin_email"
+if [ -z "$admin_email" ]; then
+	admin_email="${admin}@${domain}"
+    ynh_app_setting_set --app=$app --key=admin_email --value="$admin_email"
 fi
 
-if [ -z "${default_from_email:-}" ]; then
-    default_from_email="${app}@${domain}"
-    ynh_app_setting_set --app="$app" --key=default_from_email --value="$default_from_email"
+if [ -z "$default_from_email" ]; then
+	default_from_email="${app}@${domain}"
+	ynh_app_setting_set --app=$app --key=default_from_email --value="$default_from_email"
 fi
 
 #=================================================
@@ -41,76 +37,82 @@ fi
 #=================================================
 ynh_script_progression --message="Stopping systemd service '$app'..." --weight=5
 
-ynh_systemd_action --service_name="$app" --action="stop" --log_path="/var/log/$app/$app.log"
+ynh_systemd_action --service_name=$app --action="stop" --log_path="$log_file"
+
 
 #=================================================
-# PIP INSTALLATION
+# SETUP SYSTEMD
 #=================================================
-ynh_script_progression --message="Installing project via pip..." --weight=45
+ynh_script_progression --message="Configuring systemd service '$app'..." --weight=5
 
-# Always recreate everything fresh with current python version
-ynh_secure_remove "$install_dir/venv"
+ynh_add_systemd_config --service=$app --template="systemd.service"
 
-_install_fmd_venv
-
-chmod o-rwx "$install_dir"
-chown -R "$app:www-data" "$install_dir"
+#=================================================
+# PYTHON VIRTUALENV
+#=================================================
+ynh_script_progression --message="Create and setup Python virtualenv..." --weight=45
+cp ../conf/requirements.txt "$data_dir/requirements.txt"
+myynh_setup_python_venv
 
 #=================================================
 # copy config files
 # ================================================
-ynh_script_progression --message="Create $app configuration files..."
+ynh_script_progression --message="Create project configuration files..."
 
-ynh_add_config --template="gunicorn.conf.py" --destination="$install_dir/gunicorn.conf.py"
+ynh_add_config --template="gunicorn.conf.py" --destination="$data_dir/gunicorn.conf.py"
 
-ynh_add_config --template="manage.py" --destination="$install_dir/manage.py"
-chmod +x "$install_dir/manage.py"
+ynh_add_config --template="manage.py" --destination="$data_dir/manage.py"
+chmod -c +x "$data_dir/manage.py"
 
-ynh_add_config --template="settings.py" --destination="$install_dir/settings.py"
-ynh_add_config --template="setup_user.py" --destination="$install_dir/setup_user.py"
-ynh_add_config --template="urls.py" --destination="$install_dir/urls.py"
-ynh_add_config --template="wsgi.py" --destination="$install_dir/wsgi.py"
+ynh_add_config --template="settings.py" --destination="$data_dir/settings.py"
+ynh_add_config --template="setup_user.py" --destination="$data_dir/setup_user.py"
+ynh_add_config --template="urls.py" --destination="$data_dir/urls.py"
+ynh_add_config --template="wsgi.py" --destination="$data_dir/wsgi.py"
 
 #=================================================
 # MIGRATE PYINVENTORY
 #=================================================
 ynh_script_progression --message="migrate/collectstatic/createadmin..." --weight=10
 
-pushd "$install_dir"
-    # Just for debugging:
-    ynh_exec_as "$app" "$venvpython" ./manage.py diffsettings
+cd "$data_dir" || exit
 
-    ynh_exec_as "$app" "$venvpython" ./manage.py migrate --no-input
-    ynh_exec_as "$app" "$venvpython" ./manage.py collectstatic --no-input
+# Just for debugging:
+./manage.py diffsettings
 
-    # Create/update Django superuser (set unusable password, because auth done via SSOwat):
-    ynh_exec_as "$app" "$venvpython" ./manage.py create_superuser --username="$admin" --email="$(ynh_user_get_info "$admin" mail)"
+./manage.py migrate --no-input
+./manage.py collectstatic --no-input
 
-    # Check the configuration
-    # This may fail in some cases with errors, etc., but the app works and the user can fix issues later.
-    ynh_exec_as "$app" "$venvpython" ./manage.py check --deploy || true
-popd
+# Create/update Django superuser (set unusable password, because auth done via SSOwat):
+./manage.py create_superuser --username="$admin" --email="$(ynh_user_get_info "$admin" mail)"
+
+# Check the configuration
+# This may fail in some cases with errors, etc., but the app works and the user can fix issues later.
+./manage.py check --deploy || true
+
 
 #=================================================
-# REAPPLY SYSTEM CONFIGURATIONS
+# SETUP LOGROTATE
 #=================================================
-ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1
+ynh_script_progression --message="Upgrading logrotate configuration..."
 
-ynh_add_nginx_config
+# Use logrotate to manage app-specific logfile(s)
+ynh_use_logrotate --logfile="$log_file" --specific_user=$app --non-append
 
-ynh_add_systemd_config --service="$app" --template="systemd.service"
-yunohost service add "$app" --description="$app service" --log="/var/log/$app/$app.log"
-
-ynh_use_logrotate --non-append
-chmod o-rwx "/var/log/$app"
-chown -R "$app:" "/var/log/$app"
+#=================================================
+# GENERIC FINALIZATION
+#=================================================
+# SECURE FILES AND DIRECTORIES
+#=================================================
+ynh_script_progression --message="Set file permissions..."
+myynh_fix_file_permissions
 
 #=================================================
 # Start the app server via systemd
 #=================================================
 ynh_script_progression --message="Starting systemd service '$app'..." --weight=5
 
-ynh_systemd_action --service_name="$app" --action="start"
+yunohost service add $app
+ynh_systemd_action --service_name=$app --action="start" --log_path="$log_file"
 
 #=================================================
 # END OF SCRIPT
